on:
  push:
  schedule:
    - cron:  '0 6 * * 1'  # weekly check

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        qgis_image:
          - opengisch/qgis:3.34-jammy
          - opengisch/qgis:3.32-jammy
          - opengisch/qgis:3.30-jammy
          - opengisch/qgis:3.28-jammy
          - opengisch/qgis:3.22-focal
          - opengisch/qgis:focal-3.16

    env:
      QGIS_IMAGE: ${{ matrix.qgis_image }}
      API_APP_ID: ${{ secrets.API_APP_ID }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Copy .env
        run: cp .env.example .env

      - name: Run tests (${{ matrix.qgis_image }})
        run: docker-compose run tests
